/**
 * /admin/orion-logs — Founder-only review surface for the Orion
 * audit logs (Phase 3.7, Feb 28, 2026).
 *
 * Two tabs:
 *   • Queries  → reads /api/admin/orion-logs/queries
 *   • Actions  → reads /api/admin/orion-logs/actions
 *
 * Both feed off short, sanitised audit rows — no secrets, no raw
 * drafts, no private content bodies. Backend route is `_is_stealth`
 * gated, so non-founders get a 403 if they reach this page via URL.
 * We also gate at the component level to render a polite refusal.
 */
import React, { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Download, RefreshCw, Search } from "lucide-react";
import apiClient from "@/api/client";
import { useAuth } from "@/contexts/AuthContext";

const TABS = [
  { key: "queries", label: "Queries", path: "/admin/orion-logs/queries" },
  { key: "actions", label: "Actions", path: "/admin/orion-logs/actions" },
];

export default function AdminOrionLogs() {
  const { user } = useAuth();
  const isFounder = (user?.username || "").toLowerCase() === "stealth";

  const [tab, setTab] = useState("queries");
  const [summary, setSummary] = useState(null);
  const [rows, setRows] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");
  const [filters, setFilters] = useState({
    user: "",
    tool: "",
    intent: "",
    success: "",
    approval_status: "",
    since: "",
    until: "",
  });

  // Load summary once on mount (founder only).
  useEffect(() => {
    if (!isFounder) return;
    apiClient
      .get("/admin/orion-logs/summary")
      .then((r) => setSummary(r.data))
      .catch(() => setSummary(null));
  }, [isFounder]);

  // Reload the active tab whenever tab or filters change.
  useEffect(() => {
    if (!isFounder) return;
    let cancelled = false;
    setLoading(true);
    setErr("");
    const params = Object.fromEntries(
      Object.entries(filters).filter(([, v]) => v !== "" && v !== null),
    );
    if (params.success === "true") params.success = true;
    else if (params.success === "false") params.success = false;
    const path = TABS.find((t) => t.key === tab).path;
    apiClient
      .get(path, { params: { ...params, limit: 100 } })
      .then((r) => {
        if (cancelled) return;
        setRows(r.data?.rows || []);
        setTotal(r.data?.total || 0);
      })
      .catch((e) => {
        if (cancelled) return;
        setErr(e?.response?.data?.detail || "Failed to load logs.");
        setRows([]);
        setTotal(0);
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [tab, filters, isFounder]);

  if (!isFounder) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12" data-testid="orion-logs-refused">
        <div className="or-surface p-6 flex items-start gap-3">
          <AlertTriangle size={20} style={{ color: "var(--text-muted)" }} className="shrink-0 mt-0.5" />
          <div>
            <div className="font-semibold mb-1" style={{ color: "var(--text-main)" }}>Founder-only</div>
            <div className="text-sm" style={{ color: "var(--text-muted)" }}>
              The Orion audit logs are only available to the OurRealm founder.
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-6" data-testid="orion-logs-page">
      <header className="mb-5">
        <div className="text-[10px] uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
          Admin
        </div>
        <h1 className="text-2xl font-extrabold flex items-center gap-2" style={{ color: "var(--text-main)" }}>
          <Activity size={20} /> Orion audit logs
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>
          Read-only audit of every Founder/Admin analytics query and draft action
          generated by Orion. No secrets, raw drafts, or private content are persisted.
        </p>
      </header>

      {summary && <SummaryCard summary={summary} />}

      <div className="mt-5 flex items-center gap-2 border-b" style={{ borderColor: "var(--border-col)" }}>
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className="px-3 py-2 text-sm font-semibold"
            style={{
              color: tab === t.key ? "var(--primary)" : "var(--text-muted)",
              borderBottom: `2px solid ${tab === t.key ? "var(--primary)" : "transparent"}`,
            }}
            data-testid={`orion-logs-tab-${t.key}`}
          >
            {t.label}
          </button>
        ))}
        <div className="ml-auto text-xs" style={{ color: "var(--text-muted)" }}>
          {loading ? "Loading…" : `${total} row${total === 1 ? "" : "s"}`}
        </div>
      </div>

      <FilterBar tab={tab} filters={filters} setFilters={setFilters} />

      {err && (
        <div className="or-surface p-3 mt-3 text-sm" style={{ color: "var(--danger, #FF8080)" }}>
          {err}
        </div>
      )}

      <div className="mt-3" data-testid={`orion-logs-table-${tab}`}>
        {loading && <Skeleton />}
        {!loading && rows.length === 0 && !err && (
          <div className="or-surface p-6 text-center text-sm" style={{ color: "var(--text-muted)" }}>
            No rows match the current filters.
          </div>
        )}
        {!loading && rows.map((row, idx) => (
          tab === "queries"
            ? <QueryRow key={row.timestamp + idx} row={row} />
            : <ActionRow key={row.timestamp + idx} row={row} />
        ))}
      </div>
    </div>
  );
}


function SummaryCard({ summary }) {
  const stats = useMemo(() => ([
    { label: "Queries (all-time)", value: summary.query_total },
    { label: "Queries today",      value: summary.query_today },
    { label: "Refused (non-admin)", value: summary.query_refused },
    { label: "Actions (all-time)", value: summary.action_total },
    { label: "Actions pending",    value: summary.action_pending },
    { label: "Actions approved",   value: summary.action_approved },
  ]), [summary]);
  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2" data-testid="orion-logs-summary">
      {stats.map((s) => (
        <div key={s.label} className="or-surface p-3">
          <div className="text-[10px] uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
            {s.label}
          </div>
          <div className="text-2xl font-extrabold" style={{ color: "var(--text-main)" }}>
            {s.value}
          </div>
        </div>
      ))}
    </div>
  );
}


function FilterBar({ tab, filters, setFilters }) {
  const set = (k, v) => setFilters((prev) => ({ ...prev, [k]: v }));
  const reset = () => setFilters({
    user: "", tool: "", intent: "", success: "",
    approval_status: "", since: "", until: "",
  });
  return (
    <div className="mt-3 flex flex-wrap items-center gap-2" data-testid="orion-logs-filters">
      <div className="relative flex items-center">
        <Search size={12} className="absolute left-2" style={{ color: "var(--text-muted)" }} />
        <input
          type="text"
          className="or-input"
          style={{ paddingLeft: 26, width: 170 }}
          placeholder="user (@username)"
          value={filters.user}
          onChange={(e) => set("user", e.target.value)}
          data-testid="orion-logs-filter-user"
        />
      </div>
      <input
        type="text"
        className="or-input"
        style={{ width: 160 }}
        placeholder={tab === "queries" ? "tool name" : "tool name"}
        value={filters.tool}
        onChange={(e) => set("tool", e.target.value)}
        data-testid="orion-logs-filter-tool"
      />
      <input
        type="text"
        className="or-input"
        style={{ width: 160 }}
        placeholder={tab === "queries" ? "detected intent" : "action type"}
        value={filters.intent}
        onChange={(e) => set("intent", e.target.value)}
        data-testid="orion-logs-filter-intent"
      />
      <select
        className="or-input"
        style={{ width: 140 }}
        value={filters.success}
        onChange={(e) => set("success", e.target.value)}
        data-testid="orion-logs-filter-success"
      >
        <option value="">success: any</option>
        <option value="true">success: true</option>
        <option value="false">success: false</option>
      </select>
      {tab === "actions" && (
        <select
          className="or-input"
          style={{ width: 140 }}
          value={filters.approval_status}
          onChange={(e) => set("approval_status", e.target.value)}
          data-testid="orion-logs-filter-approval"
        >
          <option value="">approval: any</option>
          <option value="pending">pending</option>
          <option value="approved">approved</option>
          <option value="declined">declined</option>
        </select>
      )}
      <input
        type="datetime-local"
        className="or-input"
        style={{ width: 170 }}
        value={filters.since}
        onChange={(e) => set("since", e.target.value ? toIso(e.target.value) : "")}
        data-testid="orion-logs-filter-since"
        title="Since"
      />
      <input
        type="datetime-local"
        className="or-input"
        style={{ width: 170 }}
        value={filters.until}
        onChange={(e) => set("until", e.target.value ? toIso(e.target.value) : "")}
        data-testid="orion-logs-filter-until"
        title="Until"
      />
      <button
        type="button"
        onClick={reset}
        className="or-btn-ghost text-sm"
        data-testid="orion-logs-filter-reset"
      >
        <RefreshCw size={12} /> <span className="ml-1">Reset</span>
      </button>
      <button
        type="button"
        onClick={async () => {
          // Phase 3.7.4 — CSV export. Uses the same filters as the
          // current view so what you see is what you download.
          const params = Object.fromEntries(
            Object.entries(filters).filter(([, v]) => v !== "" && v !== null),
          );
          if (params.success === "true") params.success = true;
          else if (params.success === "false") params.success = false;
          const qs = new URLSearchParams(params).toString();
          const path = `/admin/orion-logs/${tab}/export${qs ? `?${qs}` : ""}`;
          try {
            // apiClient is configured with the auth header; fetch via it
            // and trigger a Blob download client-side.
            const apiClient = (await import("@/api/client")).default;
            const resp = await apiClient.get(path, { responseType: "blob" });
            const blob = new Blob([resp.data], { type: "text/csv" });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `orion-${tab}-${new Date().toISOString().slice(0,10)}.csv`;
            document.body.appendChild(a);
            a.click();
            a.remove();
            window.URL.revokeObjectURL(url);
          } catch (e) {
            // eslint-disable-next-line no-alert
            window.alert("CSV export failed. Check console.");
            // eslint-disable-next-line no-console
            console.error("[OrionLogs] export failed:", e);
          }
        }}
        className="or-btn-ghost text-sm"
        data-testid="orion-logs-export-csv"
        title="Download the filtered rows as CSV"
      >
        <Download size={12} /> <span className="ml-1">Export CSV</span>
      </button>
    </div>
  );
}

function toIso(local) {
  // Local datetime-local input → ISO UTC string.
  try { return new Date(local).toISOString(); } catch { return local; }
}


function QueryRow({ row }) {
  return (
    <div
      className="or-surface p-3 mb-2"
      data-testid={`orion-logs-query-row-${row.timestamp}`}
    >
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          <span className="text-[10px] uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
            {fmt(row.timestamp)}
          </span>
          <Pill color={row.role === "founder" ? "var(--primary)" : "var(--text-muted)"}>{row.role}</Pill>
          <span className="text-sm font-semibold" style={{ color: "var(--text-main)" }}>
            @{row.username || "unknown"}
          </span>
          {row.detected_intent && <Pill color="var(--text-muted)">{row.detected_intent}</Pill>}
          {row.tool_called && (
            <span className="text-[10px]" style={{ color: "var(--text-muted)" }}>· {row.tool_called}</span>
          )}
        </div>
        <Pill color={row.success ? "var(--ok, #22C55E)" : "var(--danger, #FF8080)"}>
          {row.success ? "success" : "fail"} · {row.execution_time_ms}ms
        </Pill>
      </div>
      <div className="mt-1.5 text-sm" style={{ color: "var(--text-main)" }}>
        “{(row.question || "").slice(0, 200)}{(row.question || "").length > 200 ? "…" : ""}”
      </div>
      {row.short_result_summary && (
        <div className="mt-1 text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
          {row.short_result_summary}
        </div>
      )}
    </div>
  );
}


function ActionRow({ row }) {
  return (
    <div
      className="or-surface p-3 mb-2"
      data-testid={`orion-logs-action-row-${row.timestamp}`}
    >
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          <span className="text-[10px] uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
            {fmt(row.timestamp)}
          </span>
          <Pill color={row.role === "founder" ? "var(--primary)" : "var(--text-muted)"}>{row.role}</Pill>
          <span className="text-sm font-semibold" style={{ color: "var(--text-main)" }}>
            @{row.username || "unknown"}
          </span>
          {row.action_type && <Pill color="var(--text-muted)">{row.action_type}</Pill>}
          {row.tool_called && (
            <span className="text-[10px]" style={{ color: "var(--text-muted)" }}>· {row.tool_called}</span>
          )}
        </div>
        <div className="flex items-center gap-1.5">
          <Pill color={approvalColor(row.approval_status)}>{row.approval_status}</Pill>
          <Pill color={row.success ? "var(--ok, #22C55E)" : "var(--danger, #FF8080)"}>
            {row.success ? "success" : "fail"} · {row.execution_time_ms}ms
          </Pill>
        </div>
      </div>
      <div className="mt-1.5 text-sm" style={{ color: "var(--text-main)" }}>
        “{(row.requested_action || "").slice(0, 200)}{(row.requested_action || "").length > 200 ? "…" : ""}”
      </div>
      <div className="mt-1 text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
        result={row.result} · prepared_draft={String(row.prepared_draft)} · confirmation_required={String(row.confirmation_required)}
      </div>
      {row.short_result_summary && (
        <div className="mt-1 text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
          {row.short_result_summary}
        </div>
      )}
    </div>
  );
}


function Pill({ children, color }) {
  return (
    <span
      className="text-[10px] uppercase tracking-widest px-1.5 py-0.5 rounded-full font-bold"
      style={{ background: `color-mix(in srgb, ${color} 18%, transparent)`, color }}
    >
      {children}
    </span>
  );
}

function approvalColor(s) {
  switch ((s || "").toLowerCase()) {
    case "approved": return "var(--ok, #22C55E)";
    case "pending":  return "var(--warn, #F59E0B)";
    case "declined": return "var(--danger, #FF8080)";
    default:         return "var(--text-muted)";
  }
}

function fmt(iso) {
  if (!iso) return "—";
  try {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    const pad = (n) => String(n).padStart(2, "0");
    return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  } catch { return iso; }
}


function Skeleton() {
  return (
    <div className="space-y-2" data-testid="orion-logs-loading">
      {[1,2,3].map((i) => (
        <div key={i} className="or-surface p-3">
          <div className="h-3 w-1/3 mb-2 rounded" style={{ background: "var(--surface-2)" }} />
          <div className="h-3 w-2/3 rounded" style={{ background: "var(--surface-2)" }} />
        </div>
      ))}
    </div>
  );
}
